### PR TITLE
Add session_traffic_source_last_click fields

### PR DESCRIPTION
**Pull request by adamribaudo-velir**
## Description & motivation
Google recently released a new set of fields, `session_traffic_source_last_click`, documented as:

```
The session_traffic_source_last_click RECORD contains the last-click attributed session traffic source data across Google ads and manual contexts, where available.
```
These fields have been added to the base package model.

## Checklist
- [X] I have verified that these changes work locally
- [ ] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [ ] I have run `dbt test` and `python -m pytest .` to validate existing tests

### CODE REVIEW

**Comment by adamribaudo-velir** [comment]
@dgitis I ran this and noticed differences between our `stg_ga4__sessions_traffic_sources_last_non_direct_daily` model and Google's `last_click` fields. When I looked at the raw events, it looked like our model was more accurate which was weird. 

I think it will only confuse people to have 2 definitions of 'session last click attribution' in the package. I suppose we should just include these fields and remove `stg_ga4__sessions_traffic_sources_last_non_direct_daily` just thought I'd check with you first.

**Comment by FloDevelops** [comment]
@adamribaudo-velir can I help to push this pull request?

**Comment by dgitis** [comment]
Sorry @FloDevelops , I'll review this now. I thought that I had reviewed it.

**Review by dgitis — APPROVED** [review]

**Comment by adamribaudo-velir** [comment]
I'll go ahead and merge. There is some overlap with these new fields and our existing 'last touch' calculated model, but offering both options does no harm. If we want to deprecate or further clarify in the future we can.

**Pull request merged**
