### PR TITLE
Support defining custom parameters that apply to all events

### PR DESCRIPTION
**Pull request by willbryant**
## Description & motivation

Make it easier to define custom parameters for all recommended events.

We define some properties in our GTM config that apply to literally all events. These aren't user properties as they do change throughout a session, but they're on every event, so it's a bit tedious to define them repeatedly in the `*_custom_parameters` sections.

We can't use YAML macros for arrays, and the DBT projects file doesn't support macros. So AFAIK there's no quick way to do this.

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [ ] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have run `dbt test` and `python -m pytest .` to validate exists tests

### CODE REVIEW

**Comment by 3v-dgudaitis** [comment]
What's the status on this? I need this for something I'm working on. I'd have to merge it into PR #46  as the client I need this for is also using that branch. I can review this when it is ready.

**Comment by dgitis** [comment]
What's the status on this? I need this for something I'm working on. I'd have to merge it into PR https://github.com/Velir/dbt-ga4/pull/46 as the client I need this for is also using that branch. I can review this when it is ready.

**Comment by willbryant** [comment]
It's ready, I'm using it in production, just waiting for someone to review it.

**Comment by willbryant** [comment]
Rebased to current `main`.

**Comment by adamribaudo-velir** [comment]
I'll review now. sorry for the delay.

**Comment by willbryant** [comment]
All good, cheers :)

**Comment by adamribaudo-velir** [comment]
@willbryant is there a reason you only added this to recommended events? Why not all events? Ex: `stg_ga4__event_click`

To be clear, we're simply copying Google's language around "Recommended events". We aren't recommending them ourselves. https://support.google.com/analytics/answer/9267735?hl=en

**Comment by willbryant** [comment]
Hmm yeah good point, I'll add them now.

**Review by adamribaudo-velir — APPROVED** [review]

**Pull request merged**
