### PR TITLE
Multi site enhancements

### PR DESCRIPTION
**Pull request by dgitis**
## Description & motivation
This PR bundles two improvements to the multi-site functionality.

**combine_property_data macro**

Switch to use `if not should_full_refresh()` rather than the `is_incremental()` macro as the is_incremental does not work in pre-hooks.

Additionally, this allows users to set the `base_ga4__events` config to use `+full-refresh: false` in the model config block as cloning on full-refreshes is prone to timing out.

This resolves issue #161. 

**friendly stream names**

Added support to map stream_ids to stream names via a seed file.

Because you can have multiple streams in a single property, this feature required an extra config parameter.

I know when I previously set this up for a different multi-site concept, Adam had requested that I implement the mapping via `dbt_project.yml` variables rather than using a seed. Using the seed works and is easy to implement.  Using a variable requires nested Jinja lists which then need to be converted into a SQL model. It's a pain to implement and I lack the time to do it right at the present.

I suggest we merge this working version and then enhance it later when people have the time to improve on it.

**documentation**

Added documentation recommending an increase to the BigQuery timeout settings when using multi-site to circumvent issue #160. 

**This PR is based off of the Time on page PR. That PR should be merged first.**

## Checklist
- [y ] I have verified that these changes work locally
- [y ] I have updated the README.md (if applicable)
- [n/a ] I have added tests & descriptions to my models (and macros if applicable)
- [ y] I have run `dbt test` and `python -m pytest .` to validate existing tests

### CODE REVIEW

**Comment by adamribaudo-velir** [comment]
is this a branch from the time on site branch? There seem to be 21 files changed.

**Comment by dgitis** [comment]
Correct @adamribaudo-velir, there's a note at the bottom of the PR's description to merge the time-on-page PR first.

**Comment by adamribaudo-velir** [comment]
@dgitis I merged in the 'time on page' branch but still getting a conflict with this branch. 

Could you separate out the 'stream rename' and 'combine_property_data macro' fix for #161? They are very different contributions. 

I'm a little skeptical that the 'stream rename' should be a part of the package - it seems like a BI layer concern in that it simply re-labels data to be human-readable. Similar to how you would use the BI layer to convert '20230329' to 'Wednesday March 29th'

**Comment by dgitis** [comment]
I'm going to close this and reopen with a cleaner PR.

**Pull request closed without merging**
