### PR TITLE
Fix engaged sessions

### PR DESCRIPTION
**Pull request by ivan-toriya-precis**
## Description & motivation

Fix session_engaged event parameter. The value should be `int_value`, not `string_value`

## Checklist
- [x] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [x] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have run `dbt test` and `python -m pytest .` to validate exists tests

### CODE REVIEW

**Comment by adamribaudo-velir** [comment]
@ivan-toriya-precis in the projects I have access to, I see `session_engaged` set as a string:
image

That's also what I see in this blog post here: https://www.ga4bigquery.com/sessions-dimensions-metrics-ga4/

Do you have any documentation from Google that is more concrete? Thanks for the PR!

**Comment by ivan-toriya-precis** [comment]
@adamribaudo-velir 
It's not documented or I just couldn't find in anywhere.
For the client I'm working with, it's in `int_value`, also double-checked with another one:
image

But, for some, I've found them **sometimes** in the `string_value` where platform = "WEB"
Weird, I'll try to investigate more about it.

**Comment by ivan-toriya-precis** [comment]
Yes, I can look into that, but probably starting next week 👍

**Comment by ivan-toriya-precis** [comment]
@adamribaudo-velir ready for review

**Review by adamribaudo-velir — APPROVED** [review]
Looks good! Thanks so much.

**Comment by eliesg** [comment]
for the enterprise client i work with, `session_engaged` can be in both int_value and string_value in a WEB only dataset:

Plein_écran_03_03_2023_07_23

So i coalesce both values:
```
(select COALESCE(value.string_value, cast(value.int_value as string)) from UNNEST(event_params) where key = 'session_engaged') as session_engaged,
```

I see you've done something similar in base_ga4__events, but with a CASE WHEN. Anyway it was just to add up on that topic :)

**Pull request merged**
